### ISSUE TITLE
Recent referrals. 

### ISSUE THREAD

**Issue by jkuruzovich** [HealthINCITE/evaluation#9]
We want a way to incorporate recent referrals.  For a evaluation date t, we want to have 2 different options. 

- Expand the widow to have "look back" where referrals before the evaluation date count as part of the prediction. [-3, 6]
- Drop predictions related to people who have recently been referred.  [-6,-3] <-wondering if something like this were you could use both look back and negative windowing.

**Comment by Nafis-Neehal-IUT** [comment]
Confused. 

- Negative window [-3,6] and Drop Recent Referrals [k] are mutually exclusive?

- Drop predictions related to people who have recently been referred. [-6,-3] <-wondering if something like this were you could use both look back and negative windowing. (What is this actually?)

- Difference between look-back and negative windowing (if there's any)?
